"""Initial migration with all 34 models

Revision ID: 92273324d41d
Revises: 
Create Date: 2026-01-13 21:55:00.252931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92273324d41d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.Enum('inspection', 'report', 'approval', 'work_request', 'finding', name='entitytype'), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation_level', sa.Enum('level_1', 'level_2', 'level_3', 'critical', name='escalationlevel'), nullable=False),
    sa.Column('notify_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_escalation_rule_active', 'escalation_rules', ['is_active'], unique=False)
    op.create_index('idx_escalation_rule_entity', 'escalation_rules', ['entity_type'], unique=False)
    op.create_index('idx_escalation_rule_name', 'escalation_rules', ['rule_name'], unique=False)
    op.create_index(op.f('ix_escalation_rules_id'), 'escalation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_escalation_rules_rule_name'), 'escalation_rules', ['rule_name'], unique=False)
    op.create_table('kpi_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('metric_value', sa.String(length=100), nullable=False),
    sa.Column('metric_unit', sa.String(length=50), nullable=True),
    sa.Column('comparison_period', sa.String(length=100), nullable=True),
    sa.Column('change_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trend', sa.Enum('up', 'down', 'stable', name='metrictrend'), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpi_calculated', 'kpi_metrics', ['calculated_at'], unique=False)
    op.create_index('idx_kpi_metric_name', 'kpi_metrics', ['metric_name'], unique=False)
    op.create_index('idx_kpi_trend', 'kpi_metrics', ['trend'], unique=False)
    op.create_index(op.f('ix_kpi_metrics_calculated_at'), 'kpi_metrics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_kpi_metrics_id'), 'kpi_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_metrics_metric_name'), 'kpi_metrics', ['metric_name'], unique=False)
    op.create_table('rbi_guidelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guideline_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('high_risk', 'medium_risk', 'low_risk', name='rbicategory'), nullable=False),
    sa.Column('inspection_frequency', sa.String(length=100), nullable=True),
    sa.Column('applicable_asset_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checklist_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rbi_guideline_active', 'rbi_guidelines', ['is_active'], unique=False)
    op.create_index('idx_rbi_guideline_category', 'rbi_guidelines', ['category'], unique=False)
    op.create_index('idx_rbi_guideline_code', 'rbi_guidelines', ['guideline_code'], unique=False)
    op.create_index(op.f('ix_rbi_guidelines_guideline_code'), 'rbi_guidelines', ['guideline_code'], unique=True)
    op.create_index(op.f('ix_rbi_guidelines_id'), 'rbi_guidelines', ['id'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inspection_type', sa.Enum('routine', 'statutory', 'rbi', 'shutdown', 'emergency', name='template_inspection_type_enum'), nullable=True),
    sa.Column('template_html', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_active', 'report_templates', ['is_active'], unique=False)
    op.create_index('idx_template_name', 'report_templates', ['name'], unique=False)
    op.create_index('idx_template_type', 'report_templates', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.create_index(op.f('ix_report_templates_name'), 'report_templates', ['name'], unique=False)
    op.create_table('system_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.Enum('api', 'database', 'redis', 'celery', 's3', 'email', name='servicename'), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'down', name='servicestatus'), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_last_check', 'system_health', ['last_check_at'], unique=False)
    op.create_index('idx_health_service', 'system_health', ['service_name'], unique=False)
    op.create_index('idx_health_status', 'system_health', ['status'], unique=False)
    op.create_index(op.f('ix_system_health_id'), 'system_health', ['id'], unique=False)
    op.create_index(op.f('ix_system_health_service_name'), 'system_health', ['service_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('inspector', 'team_leader', 'engineer', 'rbi_auditor', 'admin', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('annual_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'in_progress', 'completed', 'cancelled', name='planstatus'), nullable=False),
    sa.Column('total_inspections', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_annual_plan_dates', 'annual_plans', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_annual_plan_status', 'annual_plans', ['status'], unique=False)
    op.create_index('idx_annual_plan_year', 'annual_plans', ['year'], unique=False)
    op.create_index(op.f('ix_annual_plans_id'), 'annual_plans', ['id'], unique=False)
    op.create_index(op.f('ix_annual_plans_year'), 'annual_plans', ['year'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.Enum('pressure_vessel', 'pipeline', 'tank', 'pump', 'heat_exchanger', 'valve', 'compressor', 'other', name='assettype'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('facility', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('criticality', sa.Enum('low', 'medium', 'high', 'critical', name='assetcriticality'), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('last_inspection_date', sa.Date(), nullable=True),
    sa.Column('next_inspection_due', sa.Date(), nullable=True),
    sa.Column('rbi_category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'maintenance', 'decommissioned', name='assetstatus'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_code', 'assets', ['asset_code'], unique=False)
    op.create_index('idx_asset_criticality', 'assets', ['criticality'], unique=False)
    op.create_index('idx_asset_facility', 'assets', ['facility'], unique=False)
    op.create_index('idx_asset_location', 'assets', ['location'], unique=False)
    op.create_index('idx_asset_next_inspection', 'assets', ['next_inspection_due'], unique=False)
    op.create_index('idx_asset_status', 'assets', ['status'], unique=False)
    op.create_index('idx_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('widgets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'team', 'department', 'public', name='dashboardvisibility'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dashboard_created_by', 'dashboards', ['created_by_id'], unique=False)
    op.create_index('idx_dashboard_name', 'dashboards', ['name'], unique=False)
    op.create_index('idx_dashboard_visibility', 'dashboards', ['visibility'], unique=False)
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_dashboards_name'), 'dashboards', ['name'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('inspection', 'report', 'approval', 'work_request', 'finding', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('escalation_level', sa.Enum('level_1', 'level_2', 'level_3', 'critical', name='escalationlevel'), nullable=False),
    sa.Column('reason', sa.Enum('overdue', 'critical_finding', 'approval_stuck', 'rbi_failure', 'manual', name='escalationreason'), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('escalated_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'in_progress', 'resolved', 'cancelled', name='escalationstatus'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escalated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_escalation_assigned_to', 'escalations', ['assigned_to_id'], unique=False)
    op.create_index('idx_escalation_created', 'escalations', ['created_at'], unique=False)
    op.create_index('idx_escalation_entity', 'escalations', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_escalation_level', 'escalations', ['escalation_level'], unique=False)
    op.create_index('idx_escalation_reason', 'escalations', ['reason'], unique=False)
    op.create_index('idx_escalation_status', 'escalations', ['status'], unique=False)
    op.create_index(op.f('ix_escalations_id'), 'escalations', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('info', 'warning', 'error', 'success', 'escalation', name='notificationtype'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_entity', 'notifications', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_notification_read', 'notifications', ['is_read'], unique=False)
    op.create_index('idx_notification_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('idx_notification_user', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_token_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_token_revoked', 'refresh_tokens', ['revoked'], unique=False)
    op.create_index('idx_refresh_token_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('resource_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('available', 'on_assignment', 'on_leave', 'training', 'unavailable', name='availabilitystatus'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_availability_date', 'resource_availabilities', ['date'], unique=False)
    op.create_index('idx_availability_status', 'resource_availabilities', ['status'], unique=False)
    op.create_index('idx_availability_user', 'resource_availabilities', ['user_id'], unique=False)
    op.create_index('idx_availability_user_date', 'resource_availabilities', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_resource_availabilities_date'), 'resource_availabilities', ['date'], unique=False)
    op.create_index(op.f('ix_resource_availabilities_id'), 'resource_availabilities', ['id'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.Enum('daily_summary', 'weekly_summary', 'monthly_summary', 'quarterly_summary', 'annual_summary', 'custom', name='scheduledreporttype'), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_report_active', 'scheduled_reports', ['is_active'], unique=False)
    op.create_index('idx_scheduled_report_name', 'scheduled_reports', ['name'], unique=False)
    op.create_index('idx_scheduled_report_next_run', 'scheduled_reports', ['next_run_at'], unique=False)
    op.create_index('idx_scheduled_report_type', 'scheduled_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_id'), 'scheduled_reports', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_name'), 'scheduled_reports', ['name'], unique=False)
    op.create_table('system_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_type', sa.Enum('validation', 'database', 'external_api', 'permission', 'business_logic', 'system', name='errortype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='errorseverity'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_code', 'system_errors', ['error_code'], unique=False)
    op.create_index('idx_error_created', 'system_errors', ['created_at'], unique=False)
    op.create_index('idx_error_resolved', 'system_errors', ['resolved'], unique=False)
    op.create_index('idx_error_severity', 'system_errors', ['severity'], unique=False)
    op.create_index('idx_error_type', 'system_errors', ['error_type'], unique=False)
    op.create_index('idx_error_user', 'system_errors', ['user_id'], unique=False)
    op.create_index(op.f('ix_system_errors_error_code'), 'system_errors', ['error_code'], unique=False)
    op.create_index(op.f('ix_system_errors_id'), 'system_errors', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.String(length=500), nullable=True),
    sa.Column('setting_type', sa.Enum('string', 'number', 'boolean', 'json', name='settingtype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_setting_editable', 'system_settings', ['is_editable'], unique=False)
    op.create_index('idx_setting_key', 'system_settings', ['setting_key'], unique=False)
    op.create_index('idx_setting_type', 'system_settings', ['setting_type'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('team_leader_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_leader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_active', 'teams', ['is_active'], unique=False)
    op.create_index('idx_team_department', 'teams', ['department'], unique=False)
    op.create_index('idx_team_leader', 'teams', ['team_leader_id'], unique=False)
    op.create_index('idx_team_name', 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_last_activity', 'user_sessions', ['last_activity'], unique=False)
    op.create_index('idx_session_user', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('asset_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('technical_drawing', 'specification', 'certificate', 'manual', 'inspection_report', 'other', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_doc_asset', 'asset_documents', ['asset_id'], unique=False)
    op.create_index('idx_asset_doc_type', 'asset_documents', ['document_type'], unique=False)
    op.create_index('idx_asset_doc_uploaded', 'asset_documents', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_asset_documents_id'), 'asset_documents', ['id'], unique=False)
    op.create_table('quarterly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annual_plan_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='quarter'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'in_progress', 'completed', 'cancelled', name='planstatus'), nullable=False),
    sa.Column('total_inspections', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['annual_plan_id'], ['annual_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quarterly_plan_annual', 'quarterly_plans', ['annual_plan_id'], unique=False)
    op.create_index('idx_quarterly_plan_dates', 'quarterly_plans', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_quarterly_plan_quarter', 'quarterly_plans', ['quarter'], unique=False)
    op.create_index('idx_quarterly_plan_status', 'quarterly_plans', ['status'], unique=False)
    op.create_index(op.f('ix_quarterly_plans_id'), 'quarterly_plans', ['id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_team', sa.Enum('leader', 'senior_inspector', 'inspector', 'trainee', name='roleinteam'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_member_role', 'team_members', ['role_in_team'], unique=False)
    op.create_index('idx_team_member_team', 'team_members', ['team_id'], unique=False)
    op.create_index('idx_team_member_user', 'team_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_table('monthly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quarterly_plan_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'in_progress', 'completed', 'cancelled', name='planstatus'), nullable=False),
    sa.Column('total_inspections', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quarterly_plan_id'], ['quarterly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monthly_plan_dates', 'monthly_plans', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_monthly_plan_month', 'monthly_plans', ['month'], unique=False)
    op.create_index('idx_monthly_plan_quarterly', 'monthly_plans', ['quarterly_plan_id'], unique=False)
    op.create_index('idx_monthly_plan_status', 'monthly_plans', ['status'], unique=False)
    op.create_index(op.f('ix_monthly_plans_id'), 'monthly_plans', ['id'], unique=False)
    op.create_table('planned_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annual_plan_id', sa.Integer(), nullable=True),
    sa.Column('quarterly_plan_id', sa.Integer(), nullable=True),
    sa.Column('monthly_plan_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.Enum('routine', 'statutory', 'rbi', 'shutdown', 'emergency', name='inspectiontype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='inspectionpriority'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('estimated_duration_hours', sa.Integer(), nullable=True),
    sa.Column('assigned_team_leader_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'assigned', 'in_progress', 'completed', 'cancelled', 'rescheduled', name='plannedinspectionstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['annual_plan_id'], ['annual_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_team_leader_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monthly_plan_id'], ['monthly_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quarterly_plan_id'], ['quarterly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_planned_inspection_annual', 'planned_inspections', ['annual_plan_id'], unique=False)
    op.create_index('idx_planned_inspection_asset', 'planned_inspections', ['asset_id'], unique=False)
    op.create_index('idx_planned_inspection_date', 'planned_inspections', ['scheduled_date'], unique=False)
    op.create_index('idx_planned_inspection_monthly', 'planned_inspections', ['monthly_plan_id'], unique=False)
    op.create_index('idx_planned_inspection_priority', 'planned_inspections', ['priority'], unique=False)
    op.create_index('idx_planned_inspection_quarterly', 'planned_inspections', ['quarterly_plan_id'], unique=False)
    op.create_index('idx_planned_inspection_status', 'planned_inspections', ['status'], unique=False)
    op.create_index('idx_planned_inspection_type', 'planned_inspections', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_planned_inspections_id'), 'planned_inspections', ['id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_inspection_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.Enum('routine', 'statutory', 'rbi', 'shutdown', 'emergency', name='inspection_type_enum'), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('primary_inspector_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'on_hold', 'cancelled', name='inspectionstatus'), nullable=False),
    sa.Column('weather_conditions', sa.String(length=200), nullable=True),
    sa.Column('ambient_temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planned_inspection_id'], ['planned_inspections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_inspector_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inspection_asset', 'inspections', ['asset_id'], unique=False)
    op.create_index('idx_inspection_date', 'inspections', ['inspection_date'], unique=False)
    op.create_index('idx_inspection_inspector', 'inspections', ['primary_inspector_id'], unique=False)
    op.create_index('idx_inspection_planned', 'inspections', ['planned_inspection_id'], unique=False)
    op.create_index('idx_inspection_status', 'inspections', ['status'], unique=False)
    op.create_index('idx_inspection_type', 'inspections', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_index(op.f('ix_inspections_inspection_date'), 'inspections', ['inspection_date'], unique=False)
    op.create_table('inspector_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_inspection_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('lead', 'assistant', 'trainee', name='assignmentrole'), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'accepted', 'rejected', 'completed', 'cancelled', name='assignmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planned_inspection_id'], ['planned_inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_date', 'inspector_assignments', ['assigned_at'], unique=False)
    op.create_index('idx_assignment_inspection', 'inspector_assignments', ['planned_inspection_id'], unique=False)
    op.create_index('idx_assignment_inspector', 'inspector_assignments', ['inspector_id'], unique=False)
    op.create_index('idx_assignment_status', 'inspector_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_inspector_assignments_id'), 'inspector_assignments', ['id'], unique=False)
    op.create_table('inspection_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'pass_', 'fail', 'na', name='checklistitemstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checklist_inspection', 'inspection_checklists', ['inspection_id'], unique=False)
    op.create_index('idx_checklist_status', 'inspection_checklists', ['status'], unique=False)
    op.create_index(op.f('ix_inspection_checklists_id'), 'inspection_checklists', ['id'], unique=False)
    op.create_table('inspection_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('finding_type', sa.Enum('defect', 'observation', 'recommendation', 'ok', name='findingtype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='findingseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_on_asset', sa.String(length=200), nullable=True),
    sa.Column('measurement_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('measurement_unit', sa.String(length=50), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_finding_inspection', 'inspection_findings', ['inspection_id'], unique=False)
    op.create_index('idx_finding_severity', 'inspection_findings', ['severity'], unique=False)
    op.create_index('idx_finding_type', 'inspection_findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_inspection_findings_id'), 'inspection_findings', ['id'], unique=False)
    op.create_table('inspection_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('min_acceptable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_acceptable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_within_range', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_measurement_inspection', 'inspection_measurements', ['inspection_id'], unique=False)
    op.create_index('idx_measurement_parameter', 'inspection_measurements', ['parameter_name'], unique=False)
    op.create_index('idx_measurement_range', 'inspection_measurements', ['is_within_range'], unique=False)
    op.create_index(op.f('ix_inspection_measurements_id'), 'inspection_measurements', ['id'], unique=False)
    op.create_table('inspection_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.Enum('routine_inspection', 'statutory_inspection', 'rbi_inspection', 'shutdown_inspection', 'emergency_inspection', 'summary', name='reporttype'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'qc_pending', 'qc_approved', 'qc_rejected', 'submitted', 'approved', 'rejected', 'locked', name='reportstatus'), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('detailed_findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('conclusions', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('qc_reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('qc_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qc_comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qc_reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_generated', 'inspection_reports', ['generated_at'], unique=False)
    op.create_index('idx_report_inspection', 'inspection_reports', ['inspection_id'], unique=False)
    op.create_index('idx_report_number', 'inspection_reports', ['report_number'], unique=False)
    op.create_index('idx_report_status', 'inspection_reports', ['status'], unique=False)
    op.create_index('idx_report_type', 'inspection_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_inspection_reports_id'), 'inspection_reports', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_reports_report_number'), 'inspection_reports', ['report_number'], unique=True)
    op.create_table('approval_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.Enum('inspector', 'engineer', 'rbi', 'team_leader', name='approvalstageenum'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'approved', 'rejected', 'cancelled', name='workflowstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['inspection_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index('idx_workflow_report', 'approval_workflows', ['report_id'], unique=False)
    op.create_index('idx_workflow_stage', 'approval_workflows', ['current_stage'], unique=False)
    op.create_index('idx_workflow_status', 'approval_workflows', ['status'], unique=False)
    op.create_index(op.f('ix_approval_workflows_id'), 'approval_workflows', ['id'], unique=False)
    op.create_table('inspection_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('taken_at', sa.Date(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['inspection_findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_photo_finding', 'inspection_photos', ['finding_id'], unique=False)
    op.create_index('idx_photo_inspection', 'inspection_photos', ['inspection_id'], unique=False)
    op.create_index('idx_photo_uploaded', 'inspection_photos', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_inspection_photos_id'), 'inspection_photos', ['id'], unique=False)
    op.create_table('rbi_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'passed', 'failed', 'pending_exception', name='rbiauditstatus'), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('compliance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['inspection_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index('idx_rbi_audit_auditor', 'rbi_audits', ['auditor_id'], unique=False)
    op.create_index('idx_rbi_audit_date', 'rbi_audits', ['audit_date'], unique=False)
    op.create_index('idx_rbi_audit_report', 'rbi_audits', ['report_id'], unique=False)
    op.create_index('idx_rbi_audit_status', 'rbi_audits', ['status'], unique=False)
    op.create_index(op.f('ix_rbi_audits_id'), 'rbi_audits', ['id'], unique=False)
    op.create_table('rbi_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('guideline_id', sa.Integer(), nullable=True),
    sa.Column('exception_reason', sa.Text(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guideline_id'], ['rbi_guidelines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['inspection_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rbi_exception_approved_at', 'rbi_exceptions', ['approved_at'], unique=False)
    op.create_index('idx_rbi_exception_approved_by', 'rbi_exceptions', ['approved_by_id'], unique=False)
    op.create_index('idx_rbi_exception_guideline', 'rbi_exceptions', ['guideline_id'], unique=False)
    op.create_index('idx_rbi_exception_report', 'rbi_exceptions', ['report_id'], unique=False)
    op.create_index(op.f('ix_rbi_exceptions_id'), 'rbi_exceptions', ['id'], unique=False)
    op.create_table('report_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['inspection_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_version_created', 'report_versions', ['created_at'], unique=False)
    op.create_index('idx_version_number', 'report_versions', ['version_number'], unique=False)
    op.create_index('idx_version_report', 'report_versions', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_versions_id'), 'report_versions', ['id'], unique=False)
    op.create_table('work_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('wr_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='wrpriority'), nullable=False),
    sa.Column('wr_type', sa.Enum('corrective', 'preventive', 'replacement', 'investigation', 'other', name='wrtype'), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'in_progress', 'completed', 'cancelled', name='wrstatus'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('sap_sync_status', sa.Enum('pending', 'syncing', 'synced', 'failed', 'not_applicable', name='sapsyncstatus'), nullable=False),
    sa.Column('sap_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sap_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['inspection_findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['inspection_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wr_asset', 'work_requests', ['asset_id'], unique=False)
    op.create_index('idx_wr_created_by', 'work_requests', ['created_by_id'], unique=False)
    op.create_index('idx_wr_finding', 'work_requests', ['finding_id'], unique=False)
    op.create_index('idx_wr_inspection', 'work_requests', ['inspection_id'], unique=False)
    op.create_index('idx_wr_number', 'work_requests', ['wr_number'], unique=False)
    op.create_index('idx_wr_priority', 'work_requests', ['priority'], unique=False)
    op.create_index('idx_wr_report', 'work_requests', ['report_id'], unique=False)
    op.create_index('idx_wr_sap_status', 'work_requests', ['sap_sync_status'], unique=False)
    op.create_index('idx_wr_status', 'work_requests', ['status'], unique=False)
    op.create_index(op.f('ix_work_requests_id'), 'work_requests', ['id'], unique=False)
    op.create_index(op.f('ix_work_requests_wr_number'), 'work_requests', ['wr_number'], unique=True)
    op.create_table('approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('created', 'submitted', 'approved', 'rejected', 'returned', 'cancelled', name='approvalaction'), nullable=False),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_action', 'approval_history', ['action'], unique=False)
    op.create_index('idx_history_created', 'approval_history', ['created_at'], unique=False)
    op.create_index('idx_history_performed_by', 'approval_history', ['performed_by_id'], unique=False)
    op.create_index('idx_history_workflow', 'approval_history', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_approval_history_id'), 'approval_history', ['id'], unique=False)
    op.create_table('approval_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_review', 'approved', 'rejected', 'skipped', name='stagestatus'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stage_order', 'approval_stages', ['stage_order'], unique=False)
    op.create_index('idx_stage_reviewer', 'approval_stages', ['reviewer_id'], unique=False)
    op.create_index('idx_stage_status', 'approval_stages', ['status'], unique=False)
    op.create_index('idx_stage_workflow', 'approval_stages', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_approval_stages_id'), 'approval_stages', ['id'], unique=False)
    op.create_table('rbi_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('guideline_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('pending', 'pass_', 'fail', 'na', name='rbicheckliststatus'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('auditor_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['rbi_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guideline_id'], ['rbi_guidelines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rbi_checklist_audit', 'rbi_checklist_items', ['audit_id'], unique=False)
    op.create_index('idx_rbi_checklist_guideline', 'rbi_checklist_items', ['guideline_id'], unique=False)
    op.create_index('idx_rbi_checklist_status', 'rbi_checklist_items', ['status'], unique=False)
    op.create_index(op.f('ix_rbi_checklist_items_id'), 'rbi_checklist_items', ['id'], unique=False)
    op.create_table('wr_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wr_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('attachment', 'technical_drawing', 'approval_document', 'completion_certificate', 'other', name='wrdocumenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wr_id'], ['work_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wr_doc_type', 'wr_documents', ['document_type'], unique=False)
    op.create_index('idx_wr_doc_uploaded', 'wr_documents', ['uploaded_at'], unique=False)
    op.create_index('idx_wr_doc_wr', 'wr_documents', ['wr_id'], unique=False)
    op.create_index(op.f('ix_wr_documents_id'), 'wr_documents', ['id'], unique=False)
    op.create_table('approval_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.Enum('approval', 'rejection', 'request_changes', 'general', name='commenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['approval_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_created', 'approval_comments', ['created_at'], unique=False)
    op.create_index('idx_comment_reviewer', 'approval_comments', ['reviewer_id'], unique=False)
    op.create_index('idx_comment_stage', 'approval_comments', ['stage_id'], unique=False)
    op.create_index('idx_comment_type', 'approval_comments', ['comment_type'], unique=False)
    op.create_index(op.f('ix_approval_comments_id'), 'approval_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_comments_id'), table_name='approval_comments')
    op.drop_index('idx_comment_type', table_name='approval_comments')
    op.drop_index('idx_comment_stage', table_name='approval_comments')
    op.drop_index('idx_comment_reviewer', table_name='approval_comments')
    op.drop_index('idx_comment_created', table_name='approval_comments')
    op.drop_table('approval_comments')
    op.drop_index(op.f('ix_wr_documents_id'), table_name='wr_documents')
    op.drop_index('idx_wr_doc_wr', table_name='wr_documents')
    op.drop_index('idx_wr_doc_uploaded', table_name='wr_documents')
    op.drop_index('idx_wr_doc_type', table_name='wr_documents')
    op.drop_table('wr_documents')
    op.drop_index(op.f('ix_rbi_checklist_items_id'), table_name='rbi_checklist_items')
    op.drop_index('idx_rbi_checklist_status', table_name='rbi_checklist_items')
    op.drop_index('idx_rbi_checklist_guideline', table_name='rbi_checklist_items')
    op.drop_index('idx_rbi_checklist_audit', table_name='rbi_checklist_items')
    op.drop_table('rbi_checklist_items')
    op.drop_index(op.f('ix_approval_stages_id'), table_name='approval_stages')
    op.drop_index('idx_stage_workflow', table_name='approval_stages')
    op.drop_index('idx_stage_status', table_name='approval_stages')
    op.drop_index('idx_stage_reviewer', table_name='approval_stages')
    op.drop_index('idx_stage_order', table_name='approval_stages')
    op.drop_table('approval_stages')
    op.drop_index(op.f('ix_approval_history_id'), table_name='approval_history')
    op.drop_index('idx_history_workflow', table_name='approval_history')
    op.drop_index('idx_history_performed_by', table_name='approval_history')
    op.drop_index('idx_history_created', table_name='approval_history')
    op.drop_index('idx_history_action', table_name='approval_history')
    op.drop_table('approval_history')
    op.drop_index(op.f('ix_work_requests_wr_number'), table_name='work_requests')
    op.drop_index(op.f('ix_work_requests_id'), table_name='work_requests')
    op.drop_index('idx_wr_status', table_name='work_requests')
    op.drop_index('idx_wr_sap_status', table_name='work_requests')
    op.drop_index('idx_wr_report', table_name='work_requests')
    op.drop_index('idx_wr_priority', table_name='work_requests')
    op.drop_index('idx_wr_number', table_name='work_requests')
    op.drop_index('idx_wr_inspection', table_name='work_requests')
    op.drop_index('idx_wr_finding', table_name='work_requests')
    op.drop_index('idx_wr_created_by', table_name='work_requests')
    op.drop_index('idx_wr_asset', table_name='work_requests')
    op.drop_table('work_requests')
    op.drop_index(op.f('ix_report_versions_id'), table_name='report_versions')
    op.drop_index('idx_version_report', table_name='report_versions')
    op.drop_index('idx_version_number', table_name='report_versions')
    op.drop_index('idx_version_created', table_name='report_versions')
    op.drop_table('report_versions')
    op.drop_index(op.f('ix_rbi_exceptions_id'), table_name='rbi_exceptions')
    op.drop_index('idx_rbi_exception_report', table_name='rbi_exceptions')
    op.drop_index('idx_rbi_exception_guideline', table_name='rbi_exceptions')
    op.drop_index('idx_rbi_exception_approved_by', table_name='rbi_exceptions')
    op.drop_index('idx_rbi_exception_approved_at', table_name='rbi_exceptions')
    op.drop_table('rbi_exceptions')
    op.drop_index(op.f('ix_rbi_audits_id'), table_name='rbi_audits')
    op.drop_index('idx_rbi_audit_status', table_name='rbi_audits')
    op.drop_index('idx_rbi_audit_report', table_name='rbi_audits')
    op.drop_index('idx_rbi_audit_date', table_name='rbi_audits')
    op.drop_index('idx_rbi_audit_auditor', table_name='rbi_audits')
    op.drop_table('rbi_audits')
    op.drop_index(op.f('ix_inspection_photos_id'), table_name='inspection_photos')
    op.drop_index('idx_photo_uploaded', table_name='inspection_photos')
    op.drop_index('idx_photo_inspection', table_name='inspection_photos')
    op.drop_index('idx_photo_finding', table_name='inspection_photos')
    op.drop_table('inspection_photos')
    op.drop_index(op.f('ix_approval_workflows_id'), table_name='approval_workflows')
    op.drop_index('idx_workflow_status', table_name='approval_workflows')
    op.drop_index('idx_workflow_stage', table_name='approval_workflows')
    op.drop_index('idx_workflow_report', table_name='approval_workflows')
    op.drop_table('approval_workflows')
    op.drop_index(op.f('ix_inspection_reports_report_number'), table_name='inspection_reports')
    op.drop_index(op.f('ix_inspection_reports_id'), table_name='inspection_reports')
    op.drop_index('idx_report_type', table_name='inspection_reports')
    op.drop_index('idx_report_status', table_name='inspection_reports')
    op.drop_index('idx_report_number', table_name='inspection_reports')
    op.drop_index('idx_report_inspection', table_name='inspection_reports')
    op.drop_index('idx_report_generated', table_name='inspection_reports')
    op.drop_table('inspection_reports')
    op.drop_index(op.f('ix_inspection_measurements_id'), table_name='inspection_measurements')
    op.drop_index('idx_measurement_range', table_name='inspection_measurements')
    op.drop_index('idx_measurement_parameter', table_name='inspection_measurements')
    op.drop_index('idx_measurement_inspection', table_name='inspection_measurements')
    op.drop_table('inspection_measurements')
    op.drop_index(op.f('ix_inspection_findings_id'), table_name='inspection_findings')
    op.drop_index('idx_finding_type', table_name='inspection_findings')
    op.drop_index('idx_finding_severity', table_name='inspection_findings')
    op.drop_index('idx_finding_inspection', table_name='inspection_findings')
    op.drop_table('inspection_findings')
    op.drop_index(op.f('ix_inspection_checklists_id'), table_name='inspection_checklists')
    op.drop_index('idx_checklist_status', table_name='inspection_checklists')
    op.drop_index('idx_checklist_inspection', table_name='inspection_checklists')
    op.drop_table('inspection_checklists')
    op.drop_index(op.f('ix_inspector_assignments_id'), table_name='inspector_assignments')
    op.drop_index('idx_assignment_status', table_name='inspector_assignments')
    op.drop_index('idx_assignment_inspector', table_name='inspector_assignments')
    op.drop_index('idx_assignment_inspection', table_name='inspector_assignments')
    op.drop_index('idx_assignment_date', table_name='inspector_assignments')
    op.drop_table('inspector_assignments')
    op.drop_index(op.f('ix_inspections_inspection_date'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_index('idx_inspection_type', table_name='inspections')
    op.drop_index('idx_inspection_status', table_name='inspections')
    op.drop_index('idx_inspection_planned', table_name='inspections')
    op.drop_index('idx_inspection_inspector', table_name='inspections')
    op.drop_index('idx_inspection_date', table_name='inspections')
    op.drop_index('idx_inspection_asset', table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_planned_inspections_id'), table_name='planned_inspections')
    op.drop_index('idx_planned_inspection_type', table_name='planned_inspections')
    op.drop_index('idx_planned_inspection_status', table_name='planned_inspections')
    op.drop_index('idx_planned_inspection_quarterly', table_name='planned_inspections')
    op.drop_index('idx_planned_inspection_priority', table_name='planned_inspections')
    op.drop_index('idx_planned_inspection_monthly', table_name='planned_inspections')
    op.drop_index('idx_planned_inspection_date', table_name='planned_inspections')
    op.drop_index('idx_planned_inspection_asset', table_name='planned_inspections')
    op.drop_index('idx_planned_inspection_annual', table_name='planned_inspections')
    op.drop_table('planned_inspections')
    op.drop_index(op.f('ix_monthly_plans_id'), table_name='monthly_plans')
    op.drop_index('idx_monthly_plan_status', table_name='monthly_plans')
    op.drop_index('idx_monthly_plan_quarterly', table_name='monthly_plans')
    op.drop_index('idx_monthly_plan_month', table_name='monthly_plans')
    op.drop_index('idx_monthly_plan_dates', table_name='monthly_plans')
    op.drop_table('monthly_plans')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_index('idx_team_member_user', table_name='team_members')
    op.drop_index('idx_team_member_team', table_name='team_members')
    op.drop_index('idx_team_member_role', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_quarterly_plans_id'), table_name='quarterly_plans')
    op.drop_index('idx_quarterly_plan_status', table_name='quarterly_plans')
    op.drop_index('idx_quarterly_plan_quarter', table_name='quarterly_plans')
    op.drop_index('idx_quarterly_plan_dates', table_name='quarterly_plans')
    op.drop_index('idx_quarterly_plan_annual', table_name='quarterly_plans')
    op.drop_table('quarterly_plans')
    op.drop_index(op.f('ix_asset_documents_id'), table_name='asset_documents')
    op.drop_index('idx_asset_doc_uploaded', table_name='asset_documents')
    op.drop_index('idx_asset_doc_type', table_name='asset_documents')
    op.drop_index('idx_asset_doc_asset', table_name='asset_documents')
    op.drop_table('asset_documents')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index('idx_session_user', table_name='user_sessions')
    op.drop_index('idx_session_last_activity', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index('idx_team_name', table_name='teams')
    op.drop_index('idx_team_leader', table_name='teams')
    op.drop_index('idx_team_department', table_name='teams')
    op.drop_index('idx_team_active', table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index('idx_setting_type', table_name='system_settings')
    op.drop_index('idx_setting_key', table_name='system_settings')
    op.drop_index('idx_setting_editable', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_system_errors_id'), table_name='system_errors')
    op.drop_index(op.f('ix_system_errors_error_code'), table_name='system_errors')
    op.drop_index('idx_error_user', table_name='system_errors')
    op.drop_index('idx_error_type', table_name='system_errors')
    op.drop_index('idx_error_severity', table_name='system_errors')
    op.drop_index('idx_error_resolved', table_name='system_errors')
    op.drop_index('idx_error_created', table_name='system_errors')
    op.drop_index('idx_error_code', table_name='system_errors')
    op.drop_table('system_errors')
    op.drop_index(op.f('ix_scheduled_reports_name'), table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_id'), table_name='scheduled_reports')
    op.drop_index('idx_scheduled_report_type', table_name='scheduled_reports')
    op.drop_index('idx_scheduled_report_next_run', table_name='scheduled_reports')
    op.drop_index('idx_scheduled_report_name', table_name='scheduled_reports')
    op.drop_index('idx_scheduled_report_active', table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_resource_availabilities_id'), table_name='resource_availabilities')
    op.drop_index(op.f('ix_resource_availabilities_date'), table_name='resource_availabilities')
    op.drop_index('idx_availability_user_date', table_name='resource_availabilities')
    op.drop_index('idx_availability_user', table_name='resource_availabilities')
    op.drop_index('idx_availability_status', table_name='resource_availabilities')
    op.drop_index('idx_availability_date', table_name='resource_availabilities')
    op.drop_table('resource_availabilities')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_revoked', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notification_user', table_name='notifications')
    op.drop_index('idx_notification_type', table_name='notifications')
    op.drop_index('idx_notification_read', table_name='notifications')
    op.drop_index('idx_notification_entity', table_name='notifications')
    op.drop_index('idx_notification_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_escalations_id'), table_name='escalations')
    op.drop_index('idx_escalation_status', table_name='escalations')
    op.drop_index('idx_escalation_reason', table_name='escalations')
    op.drop_index('idx_escalation_level', table_name='escalations')
    op.drop_index('idx_escalation_entity', table_name='escalations')
    op.drop_index('idx_escalation_created', table_name='escalations')
    op.drop_index('idx_escalation_assigned_to', table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_dashboards_name'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.drop_index('idx_dashboard_visibility', table_name='dashboards')
    op.drop_index('idx_dashboard_name', table_name='dashboards')
    op.drop_index('idx_dashboard_created_by', table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_index('idx_asset_type', table_name='assets')
    op.drop_index('idx_asset_status', table_name='assets')
    op.drop_index('idx_asset_next_inspection', table_name='assets')
    op.drop_index('idx_asset_location', table_name='assets')
    op.drop_index('idx_asset_facility', table_name='assets')
    op.drop_index('idx_asset_criticality', table_name='assets')
    op.drop_index('idx_asset_code', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_annual_plans_year'), table_name='annual_plans')
    op.drop_index(op.f('ix_annual_plans_id'), table_name='annual_plans')
    op.drop_index('idx_annual_plan_year', table_name='annual_plans')
    op.drop_index('idx_annual_plan_status', table_name='annual_plans')
    op.drop_index('idx_annual_plan_dates', table_name='annual_plans')
    op.drop_table('annual_plans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_health_service_name'), table_name='system_health')
    op.drop_index(op.f('ix_system_health_id'), table_name='system_health')
    op.drop_index('idx_health_status', table_name='system_health')
    op.drop_index('idx_health_service', table_name='system_health')
    op.drop_index('idx_health_last_check', table_name='system_health')
    op.drop_table('system_health')
    op.drop_index(op.f('ix_report_templates_name'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.drop_index('idx_template_type', table_name='report_templates')
    op.drop_index('idx_template_name', table_name='report_templates')
    op.drop_index('idx_template_active', table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_rbi_guidelines_id'), table_name='rbi_guidelines')
    op.drop_index(op.f('ix_rbi_guidelines_guideline_code'), table_name='rbi_guidelines')
    op.drop_index('idx_rbi_guideline_code', table_name='rbi_guidelines')
    op.drop_index('idx_rbi_guideline_category', table_name='rbi_guidelines')
    op.drop_index('idx_rbi_guideline_active', table_name='rbi_guidelines')
    op.drop_table('rbi_guidelines')
    op.drop_index(op.f('ix_kpi_metrics_metric_name'), table_name='kpi_metrics')
    op.drop_index(op.f('ix_kpi_metrics_id'), table_name='kpi_metrics')
    op.drop_index(op.f('ix_kpi_metrics_calculated_at'), table_name='kpi_metrics')
    op.drop_index('idx_kpi_trend', table_name='kpi_metrics')
    op.drop_index('idx_kpi_metric_name', table_name='kpi_metrics')
    op.drop_index('idx_kpi_calculated', table_name='kpi_metrics')
    op.drop_table('kpi_metrics')
    op.drop_index(op.f('ix_escalation_rules_rule_name'), table_name='escalation_rules')
    op.drop_index(op.f('ix_escalation_rules_id'), table_name='escalation_rules')
    op.drop_index('idx_escalation_rule_name', table_name='escalation_rules')
    op.drop_index('idx_escalation_rule_entity', table_name='escalation_rules')
    op.drop_index('idx_escalation_rule_active', table_name='escalation_rules')
    op.drop_table('escalation_rules')
    # ### end Alembic commands ###
